<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>10</LangVersion>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <RootNamespace>$(MSBuildProjectName.Replace("-dev", ""))</RootNamespace>
        <AssemblyName>$(MSBuildProjectName.Replace("-dev", ""))</AssemblyName>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\MDD4All.EMOF.DataModels\src\MDD4All.EMOF.DataModels\MDD4All.EMOF.DataModels-dev.csproj" />
    </ItemGroup>

</Project>
